name: Build Base Image

on:
  push:
  schedule:
    - cron: '0 3 * * *' # Run every day at 3:00 AM UTC
  workflow_dispatch: # Manual trigger for debugging/testing

jobs:
  build_base:
    name: "Build Base Image"
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
      image_sha: ${{ steps.docker_build.outputs.digest }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: |
            image=moby/buildkit:master
          driver: docker-container

      - name: Generate tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/ruby-pg
          tags: |
            type=raw,value=2.6

      - name: Build and push Docker base image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432