name: Slette gamle konteinere
on:
  schedule:
    - cron: '38 1 * * *'
  workflow_dispatch:

jobs:
  delete-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ghcr cleanup action
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          dry-run: true
          keep-n-untagged: 3
