name: Cron jobs

on:
  push:
  schedule:
    - cron: '0 3 * * 0' # Run every Sunday at 3:00 AM UTC
  workflow_dispatch: # Manual trigger for debugging/testing

jobs:
  build_base:
    name: "Build Base Image"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ruby_version: "3.1"
            postgresql_version: 17
          - ruby_version: "3.2"
            postgresql_version: 17
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
      image_sha: ${{ steps.docker_build.outputs.digest }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Reset QEMU using explicit docker run commands instead of the setup-qemu-action
      # in order to prevent segmentation fault while setting libc in arm64.
      # Reference: https://github.com/docker/buildx/issues/1170
      - name: Reset QEMU
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes -c yes

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: |
            image=moby/buildkit:master
          driver: docker-container

      - name: Generate tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/ruby-pg
          tags: |
            type=raw,value=${{ matrix.ruby_version }}-pg${{ matrix.postgresql_version }}

      - name: Build and push Docker base image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./
          platforms: linux/amd64,linux/arm64/v8
          push: ${{ github.ref == 'refs/heads/main' }} # Only push on main branch
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            RUBY_VERSION=${{ matrix.ruby_version }}
            POSTGRESQL_VERSION=${{ matrix.postgresql_version }}
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432

  delete-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ghcr cleanup action
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          package: ruby-pg
          keep-n-untagged: 3
